name: CI Pipeline

on:
  pull_request:
    branches:
      - '*'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 22
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '22'

      - name: install-dependency
        run: ./mvnw install

      - name: build
        run: ./mvnw compile

      - name: ktlint
        run: ./mvnw ktlint:check

      - name: unit-test
        run: ./mvnw test