name: CI Pipeline

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 22
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '22'

      - name: Install dependencies
        run: ./mvnw install

      - name: build
        run: ./mvnw compile

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: target/
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: target/

      - name: ktlint
        run: ./mvnw ktlint:check

      - name: unit-test
        run: ./mvnw test