name: CI Pipeline

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 23
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Install dependencies
        run: ./mvnw install

      - name: Run ktlint check
        run: ./mvnw ktlint:check

      - name: Run tests
        run: ./mvnw test