name: CI Pipeline

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    env:
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      STAFF_EMAIL: ${{ secrets.STAFF_EMAIL_QA }}
      STAFF_USERNAME: ${{ secrets.STAFF_USERNAME }}
      STAFF_APPROVE_URL: ${{ secrets.STAFF_APPROVE_URL }}
      STAFF_REJECT_URL: ${{ secrets.STAFF_REJECT_URL }}

    steps:
      - name: checkout-code
        uses: actions/checkout@v3

      - name: setup-java21
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: init mongodb
        run: docker compose up -d

      - name: install-dependency
        run: ./mvnw install

      - name: build
        run: ./mvnw package

      - name: ktlint
        run: ./mvnw ktlint:check

      - name: unit-test
        run:  ./mvnw test